hyper_parameters:
  batch_size : 32
  epochs : 5
  learning_rate : 0.001

network_parameters:
  activation : 'relu'
  layer1 : "ConvLayer"
  layer2 : "ConvLayer"
  layer3 : "ConvLayer"
  forward_method : "residual"

data_scale_factor : 2